# Use an official Python runtime as a parent image
FROM python:3-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install distutils, setuptools, and required packages
RUN apt-get update && \
    apt-get install -y python3-distutils python3-setuptools python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Copy the requirements file and install dependencies
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY ./notification.py .

# Expose the necessary port
EXPOSE 5008

# Run notification.py when the container launches
CMD ["python", "./notification.py"]
