# Start with your base image
FROM python:3-slim

# Install necessary packages
RUN apt-get update && \
    apt-get install -y procps cron && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create work directory
WORKDIR /usr/src/app

# Copy your application code and entrypoint script
COPY . /usr/src/app/
COPY entrypoint.sh /usr/src/app/entrypoint.sh

# Install Python dependencies
RUN pip install -r requirements.txt

# Create the log files and set permissions
RUN touch /var/log/auto_reject.log && \
    touch /var/log/cron.log && \
    chmod 0666 /var/log/auto_reject.log && \
    chmod 0666 /var/log/cron.log

# Make scripts executable
RUN chmod +x /usr/src/app/autoreject.py && \
    chmod +x /usr/src/app/entrypoint.sh

# Set up cron job to run every minute and log its execution
RUN echo "0 0 * * * /usr/local/bin/python /usr/src/app/autoreject.py >> /var/log/auto_reject.log 2>&1\n# This extra line is required for cron to work\n" > /etc/cron.d/autoreject-cron && \
    chmod 0644 /etc/cron.d/autoreject-cron && \
    crontab /etc/cron.d/autoreject-cron

# Use the entry script as the CMD
CMD ["/usr/src/app/entrypoint.sh"]